language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ciaranoreilly/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ciaranoreilly/docker-react npm run test